"""add scanner column to companies

Revision ID: dae184441861
Revises: a83579457e4f
Create Date: 2026-07-16 18:12:20.744548+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae184441861'
down_revision: Union[str, Sequence[str], None] = 'a83579457e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('scanner', sa.String(length=100), nullable=False))
    op.drop_index(op.f('ix_companies_scanner_type'), table_name='companies')
    op.create_index(op.f('ix_companies_scanner'), 'companies', ['scanner'], unique=False)
    op.drop_column('companies', 'scanner_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('scanner_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_companies_scanner'), table_name='companies')
    op.create_index(op.f('ix_companies_scanner_type'), 'companies', ['scanner_type'], unique=False)
    op.drop_column('companies', 'scanner')
    # ### end Alembic commands ###
