"""add jobs table

Revision ID: 30aeab76de21
Revises: dae184441861
Create Date: 2026-07-16 19:01:49.957298+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30aeab76de21'
down_revision: Union[str, Sequence[str], None] = 'dae184441861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('external_job_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('employment_type', sa.String(length=100), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=True),
    sa.Column('salary', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('posted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_jobs_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('company_id', 'external_job_id', name='uq_jobs_company_external_job_id')
    )
    op.create_index(op.f('ix_jobs_company_id'), 'jobs', ['company_id'], unique=False)
    op.create_index('ix_jobs_company_id_status', 'jobs', ['company_id', 'status'], unique=False)
    op.create_index('ix_jobs_last_seen', 'jobs', ['last_seen'], unique=False)
    op.create_foreign_key(op.f('fk_job_hashes_job_id_jobs'), 'job_hashes', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_notifications_job_id_jobs'), 'notifications', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.add_column('scan_history', sa.Column('status', sa.String(), nullable=False))
    op.alter_column('scan_history', 'jobs_found',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('scan_history', 'jobs_added',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('scan_history', 'jobs_updated',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('scan_history', 'jobs_removed',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('scan_history', 'error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_scan_history_company_id'), table_name='scan_history')
    op.drop_constraint(op.f('fk_scan_history_company_id_companies'), 'scan_history', type_='foreignkey')
    op.drop_column('scan_history', 'scanner_version')
    op.drop_column('scan_history', 'duration_ms')
    op.drop_column('scan_history', 'success')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_history', sa.Column('success', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('scan_history', sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('scan_history', sa.Column('scanner_version', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_scan_history_company_id_companies'), 'scan_history', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_scan_history_company_id'), 'scan_history', ['company_id'], unique=False)
    op.alter_column('scan_history', 'error_message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('scan_history', 'jobs_removed',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('scan_history', 'jobs_updated',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('scan_history', 'jobs_added',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('scan_history', 'jobs_found',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_column('scan_history', 'status')
    op.drop_constraint(op.f('fk_notifications_job_id_jobs'), 'notifications', type_='foreignkey')
    op.drop_constraint(op.f('fk_job_hashes_job_id_jobs'), 'job_hashes', type_='foreignkey')
    op.drop_index('ix_jobs_last_seen', table_name='jobs')
    op.drop_index('ix_jobs_company_id_status', table_name='jobs')
    op.drop_index(op.f('ix_jobs_company_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
