"""add scanner to companies

Revision ID: a83579457e4f
Revises: 0001_initial_schema
Create Date: 2026-07-16 18:08:12.962876+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a83579457e4f'
down_revision: Union[str, Sequence[str], None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_companies_name'), 'companies', type_='unique')
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_index(op.f('ix_companies_scanner_type'), 'companies', ['scanner_type'], unique=False)
    op.drop_index(op.f('ix_job_hashes_job_id'), table_name='job_hashes')
    op.create_index(op.f('ix_job_hashes_content_hash'), 'job_hashes', ['content_hash'], unique=False)
    op.drop_column('job_hashes', 'recorded_at')
    op.drop_column('job_hashes', 'id')
    op.add_column('jobs', sa.Column('remote', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('posted_date', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('jobs', 'title',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('jobs', 'location',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('jobs', 'url',
               existing_type=sa.VARCHAR(length=2048),
               nullable=False)
    op.alter_column('jobs', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'REMOVED', name='job_status'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::job_status"))
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_constraint(op.f('uq_jobs_company_external_id'), 'jobs', type_='unique')
    op.create_index('ix_jobs_company_id_status', 'jobs', ['company_id', 'status'], unique=False)
    op.create_index('ix_jobs_last_seen', 'jobs', ['last_seen'], unique=False)
    op.create_unique_constraint('uq_jobs_company_external_job_id', 'jobs', ['company_id', 'external_job_id'])
    op.drop_column('jobs', 'content_hash')
    op.drop_column('jobs', 'updated_at')
    op.drop_column('jobs', 'created_at')
    op.add_column('notifications', sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_notifications_job_type'), 'notifications', type_='unique')
    op.create_index('ix_notifications_sent_at', 'notifications', ['sent_at'], unique=False)
    op.create_unique_constraint('uq_notifications_job_id_notification_type', 'notifications', ['job_id', 'notification_type'])
    op.drop_column('notifications', 'created_at')
    op.drop_column('notifications', 'updated_at')
    op.add_column('scan_history', sa.Column('duration_ms', sa.Integer(), nullable=True))
    op.add_column('scan_history', sa.Column('scanner_version', sa.String(length=50), nullable=False))
    op.add_column('scan_history', sa.Column('success', sa.Boolean(), server_default='0', nullable=False))
    op.alter_column('scan_history', 'error_message',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('scan_history', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_history', sa.Column('status', postgresql.ENUM('RUNNING', 'SUCCESS', 'FAILED', name='scan_status'), server_default=sa.text("'RUNNING'::scan_status"), autoincrement=False, nullable=False))
    op.alter_column('scan_history', 'error_message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
    op.drop_column('scan_history', 'success')
    op.drop_column('scan_history', 'scanner_version')
    op.drop_column('scan_history', 'duration_ms')
    op.add_column('notifications', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint('uq_notifications_job_id_notification_type', 'notifications', type_='unique')
    op.drop_index('ix_notifications_sent_at', table_name='notifications')
    op.create_unique_constraint(op.f('uq_notifications_job_type'), 'notifications', ['job_id', 'notification_type'], postgresql_nulls_not_distinct=False)
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('notifications', 'sent_at')
    op.add_column('jobs', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint('uq_jobs_company_external_job_id', 'jobs', type_='unique')
    op.drop_index('ix_jobs_last_seen', table_name='jobs')
    op.drop_index('ix_jobs_company_id_status', table_name='jobs')
    op.create_unique_constraint(op.f('uq_jobs_company_external_id'), 'jobs', ['company_id', 'external_job_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.alter_column('jobs', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('ACTIVE', 'REMOVED', name='job_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::job_status"))
    op.alter_column('jobs', 'url',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
    op.alter_column('jobs', 'location',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('jobs', 'title',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('jobs', 'posted_date')
    op.drop_column('jobs', 'remote')
    op.add_column('job_hashes', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('job_hashes', sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_job_hashes_content_hash'), table_name='job_hashes')
    op.create_index(op.f('ix_job_hashes_job_id'), 'job_hashes', ['job_id'], unique=False)
    op.drop_index(op.f('ix_companies_scanner_type'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.create_unique_constraint(op.f('uq_companies_name'), 'companies', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
