companies:
  - name: ciena
    scanner: workday
    url: https://ciena.wd5.myworkdayjobs.com/wday/cxs/ciena/Careers/jobs

  - name: NAV Canada
    scanner: workday
    url: https://navcanada.wd10.myworkdayjobs.com/wday/cxs/navcanada/NAV_Careers/jobs
  - name: QNX 
    scanner: workday 
    url: https://bb.wd3.myworkdayjobs.com/wday/cxs/bb/QNX/jobs 
  
  - name: TMX 
    scanner: workday 
    url: https://tmx.wd3.myworkdayjobs.com/wday/cxs/tmx/TMX_Careers/jobs