filters:
  include_keywords:
    - python
    - backend
    - java
    - engineer
    - c/c++

  exclude_keywords:
    - senior
    - manager
    - director
    - lead
  locations:
    - Toronto
    - Canada
    - Ottawa
    - Montreal
  remote: false
  intern_keywords:
    - intern
    - internship
    - coop
  new_grad_keywords:
    - new grad
    - graduate
  junior_keywords:
    - junior
    - entry level